apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-lb
  namespace: go-application
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: girishcodelachemy
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: go-application-svc
                port:
                  number: 80